PAGE_COLOR = "gray"
COURSE_COLOR = "green"
COURSELET_COLOR = "olive"
REVIEW_COLOR = "bisque"
USER_COLOR = "red"
EPOCH_NODE_COLOR = "peachpuff"
ORDER_COLOR = "blue"

PAGE_BASE = "pv"
COURSE_BASE = "course"
COURSELET_BASE = "courselet"
USER_BASE = "user"
REVIEW_BASE = "review"
ORDER_BASE = "order"